services:
  postgres:
    image: postgres:latest
    container_name: rushy-preview--postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rushy-preview
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: rushy-preview--redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
    driver: local
